# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KisanHubFileParser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.4'
  # Pods for KisanHubFileParser

  target 'KisanHubFileParserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KisanHubFileParserUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
